# Site information
title: "O que faço com esses números?"
author: "Renato Pedroso Lauris"
description: "Algumas digressões sobre gastos públicos, auditoria, estatística e políticas públicas usando dados." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
# baseurl: ""
# url: ""

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "example@mail.com"
twitter_username: "renatolauris"
github_username: "renatolauris"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

# Site settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

disqus:
  shortname: renatolauris
#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
#theme: "minima"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
