project:
  type: website
  output-dir: docs

website:
  title: "Página do Renato Lauris"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
format:
  html:
    theme:
      light: minty
      dark: zephyr
    css: styles.css
    toc: true

editor: visual
page-layout: full
